trigger:
  branches:
    include:
      - main
      - dev
      - qa

pool:
  name: Test

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: Test
    steps:
    - script: echo "Hello, world!" > helloworld.txt
      displayName: 'Create Hello World File'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/helloworld.txt'
        ArtifactName: 'helloworld'
      displayName: 'Publish Hello World Artifact'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy Job'
    environment: 'Dev'  # Deploy to the 'Dev' environment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'helloworld'
          - script: |
               type "$(Pipeline.Workspace)/helloworld/helloworld.txt"
            displayName: 'Deploy Hello World'
