# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Test

steps:
- script: echo "Hello, world!" > helloworld.txt
  displayName: 'Create Hello World File'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/helloworld.txt'
    ArtifactName: 'helloworld'
  displayName: 'Publish Hello World Artifact'

