trigger:
  branches:
    include:
      - main
      - dev
      - qa

pool:
  name: Test

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      name: Test
    steps:
    - script: echo "Hello, world!" > helloworld.txt
      displayName: 'Create Hello World File'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/helloworld.txt'
        ArtifactName: 'helloworld'
      displayName: 'Publish Hello World Artifact'

- stage: DeployToDev
  displayName: 'Deploy to Dev Stage'
  dependsOn: Build
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/dev')))
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Dev Job'
    environment: 'Dev'  # Deploy to the 'Dev' environment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'helloworld'
          - script: |
               type "$(Pipeline.Workspace)\helloworld\helloworld.txt"
            displayName: 'Deploy Hello World'

- stage: DeployToQa
  displayName: 'Deploy to Qa Stage'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Qa Job'
    environment: 'Qa'  # Deploy to the 'Qa' environment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'helloworld'
          - script: |
               type "$(Pipeline.Workspace)\helloworld\helloworld.txt"
            displayName: 'Deploy Hello World'
